// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OzonRepositories.Context;

#nullable disable

namespace OzonRepositories.Migrations
{
    [DbContext(typeof(OzonOrderContext))]
    [Migration("20250517174226_addcart")]
    partial class addcart
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OzonDomains.Models.AppStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("AppStatuses");
                });

            modelBuilder.Entity("OzonDomains.Models.ColumnMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColumnMappingsSerialized")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("ManufacturerFromArticle")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MappingName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("SelectedClientId")
                        .HasColumnType("int");

                    b.Property<int?>("SelectedCurrencyCode")
                        .HasColumnType("int");

                    b.Property<int?>("SelectedManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("SelectedStatus")
                        .HasColumnType("longtext");

                    b.Property<int?>("SelectedSupplierId")
                        .HasColumnType("int");

                    b.Property<int?>("SelectedWarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SelectedClientId");

                    b.HasIndex("SelectedManufacturerId");

                    b.HasIndex("SelectedSupplierId");

                    b.HasIndex("SelectedWarehouseId");

                    b.ToTable("ColumnMappings");
                });

            modelBuilder.Entity("OzonDomains.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Currencys");
                });

            modelBuilder.Entity("OzonDomains.Models.FileUploadRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FileUploadRecords");
                });

            modelBuilder.Entity("OzonDomains.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("OzonDomains.Models.MatchedRowSys.MatchedResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MainFileName")
                        .HasColumnType("longtext");

                    b.Property<string>("ScondaryFileName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("СreationDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("MatchedResults");
                });

            modelBuilder.Entity("OzonDomains.Models.MatchedRowSys.MatchedRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("File1DataSerialized")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("File2DataSerialized")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("MatchedResultId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchedResultId");

                    b.ToTable("MatchedRows");
                });

            modelBuilder.Entity("OzonDomains.Models.MatchedRowSys.MatchingColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Item1")
                        .HasColumnType("longtext");

                    b.Property<string>("Item2")
                        .HasColumnType("longtext");

                    b.Property<int?>("MatchedResultId")
                        .HasColumnType("int");

                    b.Property<int?>("SavedMatchingColumnId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchedResultId");

                    b.HasIndex("SavedMatchingColumnId");

                    b.ToTable("MatchingColumns");
                });

            modelBuilder.Entity("OzonDomains.Models.MatchedRowSys.SavedMatchingColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StartColumn1")
                        .HasColumnType("int");

                    b.Property<int>("StartColumn2")
                        .HasColumnType("int");

                    b.Property<int>("StartRow1")
                        .HasColumnType("int");

                    b.Property<int>("StartRow2")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SavedMatchingColumns");
                });

            modelBuilder.Entity("OzonDomains.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Article")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal?>("CostPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("DeliveryCity")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("EtProducerId")
                        .HasColumnType("int");

                    b.Property<int?>("ExcelFileDataId")
                        .HasColumnType("int");

                    b.Property<bool?>("FromFile")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("FromFiletId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsReturnable")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastStatusChangeDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("MaxCommissionInfo")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("MaxDiscount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("MaxOzonCommission")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("MaxProfit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("MinCommissionInfo")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("MinDiscount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("MinOzonCommission")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("MinProfit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("NewCategory")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OrderNumberToSupplier")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("OriginalPurchasePrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("OzonClientId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("ProcessingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ProductInfoId")
                        .HasColumnType("int");

                    b.Property<string>("ProductKey")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProductName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("ShipmentAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ShipmentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("ShipmentWarehouseId")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<DateTime?>("ShippingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedColumns")
                        .HasColumnType("longtext");

                    b.Property<int?>("СurrencyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppStatusId");

                    b.HasIndex("ExcelFileDataId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("OzonClientId");

                    b.HasIndex("ProductInfoId");

                    b.HasIndex("ShipmentWarehouseId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("СurrencyId");

                    b.ToTable("Orders", (string)null);

                    b.HasAnnotation("SqlServer:IsTemporal", true);
                });

            modelBuilder.Entity("OzonDomains.Models.OrderCart.CartStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CartStatuses");
                });

            modelBuilder.Entity("OzonDomains.Models.OrderCart.ItemStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ItemStatuses");
                });

            modelBuilder.Entity("OzonDomains.Models.OrderCart.OrderCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CartStatusId")
                        .HasColumnType("int");

                    b.Property<string>("ClientOrderNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Comment")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CartStatusId");

                    b.ToTable("OrderCarts");
                });

            modelBuilder.Entity("OzonDomains.Models.OrderCart.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("ItemStatusId")
                        .HasColumnType("int");

                    b.Property<int>("OrderCartId")
                        .HasColumnType("int");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StudioOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ItemStatusId");

                    b.HasIndex("OrderCartId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("OzonDomains.Models.OrdersFileMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FolderName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("OrdersFileMetadata");
                });

            modelBuilder.Entity("OzonDomains.Models.OzonClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ClientType")
                        .HasColumnType("int");

                    b.Property<int>("CurrencyCode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("OzonClients");
                });

            modelBuilder.Entity("OzonDomains.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Article")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CommercialCategory")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("CurrentPriceWithDiscount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("FboOzonSkuId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FbsOzonSkuId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OzonProductId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double?>("Volume")
                        .HasColumnType("double");

                    b.Property<double?>("VolumetricWeight")
                        .HasColumnType("double");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("OzonDomains.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CostFactor")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("CsvUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("CurrencyCode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("WeightFactor")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("WeightFactorCurrencyCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("OzonDomains.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("OzonDomains.Models.UserAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvailableOrderColumns")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UserAccess");
                });

            modelBuilder.Entity("OzonDomains.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("OzonDomains.Models.ColumnMapping", b =>
                {
                    b.HasOne("OzonDomains.Models.OzonClient", "SelectedClient")
                        .WithMany()
                        .HasForeignKey("SelectedClientId");

                    b.HasOne("OzonDomains.Models.Manufacturer", "SelectedManufacturer")
                        .WithMany()
                        .HasForeignKey("SelectedManufacturerId");

                    b.HasOne("OzonDomains.Models.Supplier", "SelectedSupplier")
                        .WithMany()
                        .HasForeignKey("SelectedSupplierId");

                    b.HasOne("OzonDomains.Models.Warehouse", "SelectedWarehouse")
                        .WithMany()
                        .HasForeignKey("SelectedWarehouseId");

                    b.Navigation("SelectedClient");

                    b.Navigation("SelectedManufacturer");

                    b.Navigation("SelectedSupplier");

                    b.Navigation("SelectedWarehouse");
                });

            modelBuilder.Entity("OzonDomains.Models.MatchedRowSys.MatchedRow", b =>
                {
                    b.HasOne("OzonDomains.Models.MatchedRowSys.MatchedResult", null)
                        .WithMany("MatchedRows")
                        .HasForeignKey("MatchedResultId");
                });

            modelBuilder.Entity("OzonDomains.Models.MatchedRowSys.MatchingColumn", b =>
                {
                    b.HasOne("OzonDomains.Models.MatchedRowSys.MatchedResult", null)
                        .WithMany("MatchedColumns")
                        .HasForeignKey("MatchedResultId");

                    b.HasOne("OzonDomains.Models.MatchedRowSys.SavedMatchingColumn", null)
                        .WithMany("MatchingColumns")
                        .HasForeignKey("SavedMatchingColumnId");
                });

            modelBuilder.Entity("OzonDomains.Models.Order", b =>
                {
                    b.HasOne("OzonDomains.Models.AppStatus", "AppStatus")
                        .WithMany()
                        .HasForeignKey("AppStatusId");

                    b.HasOne("OzonDomains.Models.OrdersFileMetadata", "ExcelFileData")
                        .WithMany()
                        .HasForeignKey("ExcelFileDataId");

                    b.HasOne("OzonDomains.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");

                    b.HasOne("OzonDomains.Models.OzonClient", "OzonClient")
                        .WithMany()
                        .HasForeignKey("OzonClientId");

                    b.HasOne("OzonDomains.Models.Product", "ProductInfo")
                        .WithMany()
                        .HasForeignKey("ProductInfoId");

                    b.HasOne("OzonDomains.Models.Warehouse", "ShipmentWarehouse")
                        .WithMany()
                        .HasForeignKey("ShipmentWarehouseId");

                    b.HasOne("OzonDomains.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId");

                    b.HasOne("OzonDomains.Models.Transaction", null)
                        .WithMany("Orders")
                        .HasForeignKey("TransactionId");

                    b.HasOne("OzonDomains.Models.Currency", "Сurrency")
                        .WithMany()
                        .HasForeignKey("СurrencyId");

                    b.Navigation("AppStatus");

                    b.Navigation("ExcelFileData");

                    b.Navigation("Manufacturer");

                    b.Navigation("OzonClient");

                    b.Navigation("ProductInfo");

                    b.Navigation("ShipmentWarehouse");

                    b.Navigation("Supplier");

                    b.Navigation("Сurrency");
                });

            modelBuilder.Entity("OzonDomains.Models.OrderCart.OrderCart", b =>
                {
                    b.HasOne("OzonDomains.Models.OrderCart.CartStatus", "CartStatus")
                        .WithMany("OrderCarts")
                        .HasForeignKey("CartStatusId");

                    b.Navigation("CartStatus");
                });

            modelBuilder.Entity("OzonDomains.Models.OrderCart.OrderItem", b =>
                {
                    b.HasOne("OzonDomains.Models.OrderCart.ItemStatus", "ItemStatus")
                        .WithMany("OrderItems")
                        .HasForeignKey("ItemStatusId");

                    b.HasOne("OzonDomains.Models.OrderCart.OrderCart", "OrderCart")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemStatus");

                    b.Navigation("OrderCart");
                });

            modelBuilder.Entity("OzonDomains.Models.MatchedRowSys.MatchedResult", b =>
                {
                    b.Navigation("MatchedColumns");

                    b.Navigation("MatchedRows");
                });

            modelBuilder.Entity("OzonDomains.Models.MatchedRowSys.SavedMatchingColumn", b =>
                {
                    b.Navigation("MatchingColumns");
                });

            modelBuilder.Entity("OzonDomains.Models.OrderCart.CartStatus", b =>
                {
                    b.Navigation("OrderCarts");
                });

            modelBuilder.Entity("OzonDomains.Models.OrderCart.ItemStatus", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("OzonDomains.Models.OrderCart.OrderCart", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("OzonDomains.Models.Transaction", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
